SITE_URL = "https://www.wetakefwd.online"

SERVICES = [
    dict(slug="ai-business-automation", title="AI Business Automation", short_title="AI business automation", category="AUTOMATE", summary="Remove repetitive steps and connect the systems your team already uses.", intro="Business automation connects repeated tasks, data and decisions across your existing tools. We identify the manual steps that slow your team down, then design a workflow with clear ownership and human review where it matters.", detail="A typical first phase could capture an enquiry, send it to the right person, create a CRM record and schedule a follow-up. We begin with the process and success measure before choosing tools.", includes=["Workflow mapping and prioritisation", "Integrations with existing tools", "Approvals, alerts and exception handling", "Documentation and ongoing improvement"], use_case="For a service business, an enquiry from a website can be logged, assigned, acknowledged and followed up without copying details between tools.", faq=[("What should we automate first?", "Start with a repetitive process that takes measurable time or causes missed opportunities. We assess volume, complexity and risk before recommending a first build.")]),
    dict(slug="ai-agents-chatbots", title="AI Agents & Chatbots", short_title="AI agents & chatbots", category="AI SYSTEMS", summary="Give customers and teams faster answers with a reliable human handoff.", intro="AI agents and chatbots can answer questions, search approved knowledge and help people complete routine tasks. The useful version is grounded in your actual business information and has a clear escalation path.", detail="We define what the assistant is allowed to do, connect the right sources, test common and difficult questions, and make it easy for a person to take over.", includes=["Website support assistants", "Internal knowledge assistants", "Lead qualification flows", "Testing, guardrails and escalation"], use_case="A support assistant can answer repeated questions about services and pass complex enquiries to a team member with the relevant context.", faq=[("Will the chatbot invent answers?", "No AI assistant is perfect. We reduce errors with approved sources, scoped tasks, testing and a clear human handoff.")]),
    dict(slug="whatsapp-crm-automation", title="WhatsApp & CRM Automation", short_title="WhatsApp & CRM", category="CUSTOMER JOURNEY", summary="Keep enquiries organised and follow up without losing context.", intro="WhatsApp and CRM automation helps teams capture, organise and respond to conversations consistently. It connects the first enquiry to assignment, follow-up and reporting.", detail="We map consent and messaging requirements, then design workflows that fit your team rather than burying them under notifications.", includes=["Lead capture and CRM setup", "Conversation routing", "Follow-up reminders and templates", "Pipeline visibility"], use_case="An incoming WhatsApp enquiry can be categorised, assigned and recorded so the next team member knows what happened.", faq=[("Can this work with our current CRM?", "Often yes, if your CRM exposes suitable integrations or APIs. We review the existing setup before estimating work.")]),
    dict(slug="lead-generation", title="Lead Generation", short_title="Lead generation", category="GROWTH", summary="Make the path from first visit to meaningful enquiry easier to follow.", intro="Lead generation is the combined work of reaching the right audience, explaining your offer and making it simple to enquire. The goal is a measurable pipeline, not just more form submissions.", detail="We can align landing pages, campaigns, tracking and follow-up so your team sees where enquiries come from and what happens next.", includes=["Audience and offer planning", "Landing pages and forms", "Conversion tracking", "Lead handoff and follow-up"], use_case="A local service campaign can send relevant visitors to a focused page with a clear call to action and an organised response process.", faq=[("Do you guarantee a number of leads?", "No. Lead volume and quality depend on the offer, budget, competition and sales process. We define measurable work and optimise from real data.")]),
    dict(slug="website-app-development", title="Website & App Development", short_title="Websites & apps", category="BUILD", summary="Create fast, accessible digital experiences that help people take action.", intro="A website or app should explain the business clearly and make important tasks easy. We design and build pages, portals and applications around real users and business goals.", detail="We consider content structure, mobile use, performance, accessibility and search visibility from the beginning.", includes=["Business websites and landing pages", "Web apps and portals", "Mobile-friendly interfaces", "Analytics and maintenance planning"], use_case="A new business website can combine service explanations, clear contact paths and the technical foundations search engines need to crawl it.", faq=[("Can you improve an existing website?", "Yes. We review the current site, identify what is useful, and scope the highest-value improvements.")]),
    dict(slug="meta-google-ads", title="Meta & Google Ads", short_title="Meta & Google Ads", category="MARKET", summary="Run focused campaigns with clear landing pages and useful reporting.", intro="Paid advertising can create demand or capture existing intent. We plan campaigns around the audience, offer and next step, then connect the ads to a relevant page and lead handling process.", detail="Meta and Google campaigns need ongoing review. We look at search terms, creative, audience fit, conversion data and lead quality.", includes=["Campaign planning and setup", "Creative and landing page direction", "Conversion tracking", "Ongoing optimisation and reporting"], use_case="A Google search campaign for a high-intent service can connect to a dedicated page and feed enquiries into your CRM.", faq=[("Is ad spend included?", "Media spend is normally paid directly to the advertising platform. Management and production scope are quoted separately.")]),
    dict(slug="seo-services", title="SEO Services", short_title="SEO", category="SEARCH", summary="Make your expertise easier for search engines and customers to understand.", intro="Search engine optimisation improves how a site is structured, crawled and understood while helping visitors find useful answers. It combines technical work, service content and earned authority.", detail="We prioritise accurate pages, clear internal links, performance, structured data where appropriate and reporting through search tools.", includes=["Technical SEO review", "Service page architecture", "On-page content and internal links", "Search Console and measurement guidance"], use_case="A service business can publish dedicated pages that explain each offer, answer real buyer questions and connect to relevant next steps.", faq=[("Can you guarantee first place on Google?", "No agency can guarantee a ranking. We improve the site and content while tracking what search engines actually show.")]),
    dict(slug="social-content", title="Social Media & Content", short_title="Social & content", category="MARKET", summary="Explain your offer consistently across the places your buyers pay attention.", intro="Content works when it reflects real expertise, answers customer questions and supports the sales conversation. We can plan and create social posts, website copy and campaign assets around your positioning.", detail="The content calendar should serve a purpose: explaining a service, addressing an objection or showing authentic work.", includes=["Content strategy and calendars", "Social posts and creative", "Website and landing page copy", "Measurement and refinement"], use_case="A recurring set of educational posts can turn common customer questions into useful explanations linked back to service pages.", faq=[("Can you create case studies?", "Yes, when there is a real project, permission to share it and evidence we can verify.")]),
    dict(slug="custom-software", title="Custom Software", short_title="Custom software", category="BUILD", summary="Build operational tools around your business instead of forcing awkward workarounds.", intro="Custom software is useful when a critical workflow does not fit off-the-shelf tools. We can scope dashboards, portals, CRM features and operational systems based on the people who use them.", detail="We begin with the smallest reliable release, define roles and data needs, then plan integrations, security and ongoing ownership.", includes=["Workflow and product discovery", "Dashboards and portals", "CRM, ERP and process tools", "Integrations and maintenance"], use_case="A school could bring admission enquiries, student records and staff workflows into a single role-based system.", faq=[("Do we own the software?", "Ownership, hosting, access and support terms are agreed in the proposal before work starts.")]),
    dict(slug="ongoing-support", title="Ongoing Support", short_title="Ongoing support", category="CARE", summary="Keep digital systems current, useful and aligned with changing priorities.", intro="A launch is the start of a working system. Ongoing support keeps websites, automation and campaigns maintained while new information and user feedback guide improvements.", detail="We can agree a support scope that covers monitoring, updates, small enhancements and periodic review, with clear response expectations.", includes=["Maintenance and updates", "Performance and issue review", "Reporting and recommendations", "Prioritised improvements"], use_case="After a new lead flow launches, support can address broken integrations, adjust messaging and improve conversion paths over time.", faq=[("Is support available after launch?", "Yes. We scope ongoing support around the systems delivered and the level of help your team needs.")]),
]

HOME_FAQ = [
    dict(question="What does WeTakeFWD do?", answer="WeTakeFWD is an AI Automation & Digital Growth Agency. We connect websites, marketing, lead generation, AI systems and business automation so digital work supports a clear business goal."),
    dict(question="Can you work with our existing website or CRM?", answer="Yes. We review what you already use, keep what works and plan integrations or improvements around the gaps."),
    dict(question="Do we need an AI solution?", answer="Not always. We first identify the bottleneck. A better website, clearer campaign or simpler workflow may be the right first step."),
    dict(question="How do projects begin?", answer="We start with a discovery conversation, review the goal and current setup, then propose a scoped first phase with deliverables and timeline."),
    dict(question="Can you guarantee rankings or sales?", answer="No. Search rankings and sales depend on many factors. We can define the work we control, measure progress and improve the system over time."),
]
